version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-source-contentful
    versions:
    - 4.6.2
  - dependency-name: markdown-to-jsx
    versions:
    - 7.1.1
  - dependency-name: react
    versions:
    - 17.0.1
